---
title: "Background"
author: Birgir Hrafnkelsson
date:
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Background}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path='figs-introduction/',
  fig.align='center',
  prompt=T
)
```
Most methods for directly measuring the discharge of a water stream are time-consuming and expensive. Therefore, indirect methods for measuring the discharge are usually applied. A popular method for inferring discharge is to fit a model that describes the relationship between discharge and water level, also referred to as stage. Such a model is called a discharge rating curve, and one, widely used in hydrology, is the power-law rating curve, $Q(h)=a(h-c)^b$, where $Q(h)$ is the discharge, $h$ is the water stage, and $a$, $b$ and $c$ are constants. However, the power-law rating curve is not always able to adequately describe the relationship between discharge and stage. Hrafnkelsson et al. (2020) proposed a novel extension to the power-law rating curve referred to as the generalized power-law rating curve. Its form is $Q(h)=a(h-c)^{f(h)}$, where the power-law exponent, $f(h)$, is a function of stage. This generalization allows the water stream cross-section's geometry to affect the power-law exponent and thus lends more flexibility to the rating curve to adequately describe the relationship between discharge and stage.

## Bayesian Generalized Power-Law Rating Curves

The power-law model is commonly assumed in hydraulic practice to fit rating curves, and as mention above, its form is

$$Q(h) = a(h-c)^{b}$$ (1)
where $Q$, $h$, $a$, $b$ and $c$ are as before, see e.g., Venetis (1970), Clarke (1999) and Clarke et al. (2000).
The second type of rating curves is the generalized power-law model. Its construction is based on the hydraulics of open channel flow given the formulas of Chézy and Manning which are of the form

$$Q = KR^{x}AS^{1/2}$$ (2)

where $K$ is a constant, $R$ is the hydraulic radius, $x$ is constant, $A$ is the cross-section area, $S$ is the slope of the channel, further, $R = A/P$ where $P$ is the wetted perimeter. According to Chézy $x = 1/2$ while Manning claimed that $x = 2/3$ (Chow, 1959). The form of the generalized rating curve is

$$Q = a(h − c)^{f(h)}$$ (3)

where $a$ and $c$ are constants and $f(h)$ is a function of $h$ and referred to as the generalized power-law exponent. The relationship between (2) and (3) can be found by equating these two equations. In particular, the form of $f(h)$ can be derived, namely,

$$f(h) = \frac{(x+1)\{ \log A(h) - \log A(1) \}  - x \{ \log P(h) - \log P(1)  \}}{\log h}$$ (4)

Thus, $f(h)$ is a function of the constant $x$, the cross section $A$ and the wetted perimeter $P$.
The estimation approach is proposed for the estimation of the power-law model and the generalized power-law model. Bayesian inference requires specification of prior densities for unknown parameters and unknown quantities along with a full probabilistic specification of the observed data. Bayesian inference is based on the posterior density and summary statistics such as the posterior mean and 95% posterior intervals are based on the posterior density. Analytical formulas for these summary statistics are intractable in most cases and thus they are computed by generating samples from the posterior density using Markov chain Monte Carlo simulation. The Bayesian power-law model is presented on a logarithmic scale as,

$$\log(Q_i) = \log(a) + b \log(h_i -c) + \epsilon_i, \quad i = 1,...,n,$$ (5)


where $\epsilon_i$ follows a normal distribution with mean zero and variance $\sigma_{\epsilon}^2$, $n$ is the number of paired observations and $a$, $b$ and $c$ are as before. The Bayesian inference scheme implemented for the power-law model is standard, however, for efficient posterior simulation, first, samples from the joint marginal posterior density of $(c, \sigma_{\epsilon}^2)$ are obtained, then samples from the conditional posterior density of $(\log(a), b)$ conditional on $(c, \sigma_{\epsilon}^2)$ are obtained.
The Bayesian generalized power-law model is presented as a Bayesian hierarchical model. The function $f(h)$ is modeled at the latent level as $b$ plus a mean zero continuous stochastic process which is assumed to be twice mean square differentiable. The model is presented on a logarithmic scale,

$$\log (Q_i) = \log (a) + (b + \beta(h_i)) \log(h_i -c) + \varepsilon_i, \quad i = 1,...,n,$$ (6)

where $\epsilon_i$ follows a normal distribution with mean zero and variance $\sigma(h_i)_{\epsilon}^2$ that can vary with stage. Here the parameters $a$, $b$ and $c$ play a similar role as in the Bayesian power law model. The stochastic process $\beta(h)$ is assumed a priori to be a Gaussian process governed by a Matérn covariance function with smoothness parameter $\nu = 2.5$, see Matérn (1960). This model is constrained by setting $b=1.835$. An efficient posterior simulation is achieved by sampling from the joint posterior density of the hyperparameters of the model, and then sampling from the conditional density of the latent parameters conditional on the hyperparameters.


\vspace{12pt}

## References


Hrafnkelsson, B., Sigurdarson, H., and Gardarsson, S. M. (2020). *Generalization of the power-law rating curve using hydrodynamic theory and Bayesian hierarchical modeling*. arXiv preprint 2010.04769.

Clarke, R. (1999). *Uncertainty in the estimation of mean annual flood due to rating-curve indefinition.* Journal of Hydrology 222(1-4). 185–190.

Clarke, R., Mendiondo, E., Brusa L. (2000). *Uncertainties in mean discharges from two large South American rivers due to rating curve variability.* Hydrological Sciences 45(2). 221–236.

Venetis C. (1970). *A note on the estimation of the parameters in logarithmic stage-discharge relationships with estimates of their error.* International Association of Scientific Hydrology. Bulletin XV 2(6). 105–111. 

V. Chow (1959). *Open-Channel Hydraulics*. McGraw-Hill. New York.

Matérn, B. (1960). *Spatial variation. Stochastic models and their application to some problems in forest surveys and other sampling investigations.* Meddelanden från statens Skogsforskningsinstitut. 49(5).
