data(V316_river)
V316_river <- V316_river[(1:nrow(V316_river))%%2==0,]
RNGversion('3.5.0')
set.seed(1)
bplm0.fit <- bplm0(Q~W,V316_river,parallel=F)
set.seed(1)
bplm0.fit_known_c <- bplm0(Q~W,V316_river,c_param=0.8,h_max=2,parallel=F)
set.seed(1)
bplm.fit <- bplm(Q~W,V316_river,parallel=F)
set.seed(1)
bplm.fit_known_c <- bplm(Q~W,V316_river,c_param=0.8,h_max=2,parallel=F)
set.seed(1)
bgplm0.fit <- bgplm0(Q~W,V316_river,parallel=F)
set.seed(1)
bgplm0.fit_known_c <- bgplm0(Q~W,V316_river,c_param=0.8,h_max=2,parallel=F)
set.seed(1)
bgplm.fit <- bgplm(Q~W,V316_river,parallel=F)
set.seed(1)
bgplm.fit_known_c <- bgplm(Q~W,V316_river,c_param=0.8,h_max=2,parallel=F)

t_obj <- tournament(bplm0.fit,bplm.fit,bgplm0.fit,bgplm.fit)
