# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gplm_density_evaluation_unknown_c_cpp <- function(theta, P, h, B, dist, A, y, epsilon, h_min, nugget, n_unique, mu_x, Sig_ab, Z, lambda_c, lambda_sb, lambda_pb, lambda_eta_1, lambda_seta) {
    .Call(`_bdrc_gplm_density_evaluation_unknown_c_cpp`, theta, P, h, B, dist, A, y, epsilon, h_min, nugget, n_unique, mu_x, Sig_ab, Z, lambda_c, lambda_sb, lambda_pb, lambda_eta_1, lambda_seta)
}

gplm_density_evaluation_known_c_cpp <- function(theta, P, h, B, dist, A, y, epsilon, nugget, n_unique, mu_x, Sig_ab, Z, lambda_sb, lambda_pb, lambda_eta_1, lambda_seta, c) {
    .Call(`_bdrc_gplm_density_evaluation_known_c_cpp`, theta, P, h, B, dist, A, y, epsilon, nugget, n_unique, mu_x, Sig_ab, Z, lambda_sb, lambda_pb, lambda_eta_1, lambda_seta, c)
}

gplm_predict_u_unknown_c_cpp <- function(theta, x, P, B_u, h_unique, h_u, dist_all, h_min, nugget, n_unique, n_u) {
    .Call(`_bdrc_gplm_predict_u_unknown_c_cpp`, theta, x, P, B_u, h_unique, h_u, dist_all, h_min, nugget, n_unique, n_u)
}

gplm_predict_u_known_c_cpp <- function(theta, x, P, B_u, h_unique, h_u, dist_all, c, nugget, n_unique, n_u) {
    .Call(`_bdrc_gplm_predict_u_known_c_cpp`, theta, x, P, B_u, h_unique, h_u, dist_all, c, nugget, n_unique, n_u)
}

gplm0_density_evaluation_unknown_c_cpp <- function(theta, h, y, A, dist, epsilon, h_min, nugget, n_unique, mu_x, Sig_ab, Z, lambda_c, lambda_se, lambda_sb, lambda_pb) {
    .Call(`_bdrc_gplm0_density_evaluation_unknown_c_cpp`, theta, h, y, A, dist, epsilon, h_min, nugget, n_unique, mu_x, Sig_ab, Z, lambda_c, lambda_se, lambda_sb, lambda_pb)
}

gplm0_density_evaluation_known_c_cpp <- function(theta, h, y, A, dist, epsilon, c, nugget, n_unique, mu_x, Sig_ab, Z, lambda_se, lambda_sb, lambda_pb) {
    .Call(`_bdrc_gplm0_density_evaluation_known_c_cpp`, theta, h, y, A, dist, epsilon, c, nugget, n_unique, mu_x, Sig_ab, Z, lambda_se, lambda_sb, lambda_pb)
}

gplm0_predict_u_unknown_c_cpp <- function(theta, x, h_unique, h_u, dist_all, h_min, nugget, n_unique, n_u) {
    .Call(`_bdrc_gplm0_predict_u_unknown_c_cpp`, theta, x, h_unique, h_u, dist_all, h_min, nugget, n_unique, n_u)
}

gplm0_predict_u_known_c_cpp <- function(theta, x, h_unique, h_u, dist_all, c, nugget, n_unique, n_u) {
    .Call(`_bdrc_gplm0_predict_u_known_c_cpp`, theta, x, h_unique, h_u, dist_all, c, nugget, n_unique, n_u)
}

matMult <- function(A, B) {
    .Call(`_bdrc_matMult`, A, B)
}

choleskyDecomp <- function(X) {
    .Call(`_bdrc_choleskyDecomp`, X)
}

solveArma <- function(A, B) {
    .Call(`_bdrc_solveArma`, A, B)
}

matInverse <- function(A) {
    .Call(`_bdrc_matInverse`, A)
}

compute_L <- function(X, Sig_x, Sig_eps, nugget) {
    .Call(`_bdrc_compute_L`, X, Sig_x, Sig_eps, nugget)
}

compute_w <- function(L, y, X, mu_x) {
    .Call(`_bdrc_compute_w`, L, y, X, mu_x)
}

get_MCMC_summary_cpp <- function(X, h) {
    .Call(`_bdrc_get_MCMC_summary_cpp`, X, h)
}

calc_variogram_arma <- function(param_mat, i, burnin, nr_iter) {
    .Call(`_bdrc_calc_variogram_arma`, param_mat, i, burnin, nr_iter)
}

variogram_chain <- function(T_max, param_mat1, param_mat2, burnin, nr_iter) {
    .Call(`_bdrc_variogram_chain`, T_max, param_mat1, param_mat2, burnin, nr_iter)
}

distance_matrix <- function(x) {
    .Call(`_bdrc_distance_matrix`, x)
}

create_A_cpp <- function(h) {
    .Call(`_bdrc_create_A_cpp`, h)
}

pri <- function(type, args) {
    .Call(`_bdrc_pri`, type, args)
}

chain_statistics_cpp <- function(chains) {
    .Call(`_bdrc_chain_statistics_cpp`, chains)
}

plm_density_evaluation_unknown_c_cpp <- function(theta, P, h, B, y, epsilon, Sig_x, mu_x, h_min, nugget, lambda_c, lambda_eta_1, lambda_seta) {
    .Call(`_bdrc_plm_density_evaluation_unknown_c_cpp`, theta, P, h, B, y, epsilon, Sig_x, mu_x, h_min, nugget, lambda_c, lambda_eta_1, lambda_seta)
}

plm_density_evaluation_known_c_cpp <- function(theta, P, h, B, y, epsilon, Sig_x, mu_x, c, nugget, lambda_eta_1, lambda_seta) {
    .Call(`_bdrc_plm_density_evaluation_known_c_cpp`, theta, P, h, B, y, epsilon, Sig_x, mu_x, c, nugget, lambda_eta_1, lambda_seta)
}

plm_predict_u_unknown_c_cpp <- function(theta, x, P, B_u, h_u, h_min, n_u) {
    .Call(`_bdrc_plm_predict_u_unknown_c_cpp`, theta, x, P, B_u, h_u, h_min, n_u)
}

plm_predict_u_known_c_cpp <- function(theta, x, P, B_u, h_u, c) {
    .Call(`_bdrc_plm_predict_u_known_c_cpp`, theta, x, P, B_u, h_u, c)
}

plm0_density_evaluation_unknown_c_cpp <- function(theta, h, y, epsilon, Sig_ab, mu_x, h_min, nugget, lambda_c, lambda_se) {
    .Call(`_bdrc_plm0_density_evaluation_unknown_c_cpp`, theta, h, y, epsilon, Sig_ab, mu_x, h_min, nugget, lambda_c, lambda_se)
}

plm0_density_evaluation_known_c_cpp <- function(theta, h, y, epsilon, Sig_ab, mu_x, c, nugget, lambda_se) {
    .Call(`_bdrc_plm0_density_evaluation_known_c_cpp`, theta, h, y, epsilon, Sig_ab, mu_x, c, nugget, lambda_se)
}

plm0_predict_u_unknown_c_cpp <- function(theta, x, h_u, h_min) {
    .Call(`_bdrc_plm0_predict_u_unknown_c_cpp`, theta, x, h_u, h_min)
}

plm0_predict_u_known_c_cpp <- function(theta, x, h_u, c) {
    .Call(`_bdrc_plm0_predict_u_known_c_cpp`, theta, x, h_u, c)
}

