# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matMult <- function(A, B) {
    .Call(`_bdrc_matMult`, A, B)
}

matMultThree <- function(A, B, C) {
    .Call(`_bdrc_matMultThree`, A, B, C)
}

choleskyDecomp <- function(X) {
    .Call(`_bdrc_choleskyDecomp`, X)
}

solveArma <- function(A, B) {
    .Call(`_bdrc_solveArma`, A, B)
}

solveArma2 <- function(A, B) {
    .Call(`_bdrc_solveArma2`, A, B)
}

matInverse <- function(A) {
    .Call(`_bdrc_matInverse`, A)
}

compute_L <- function(X, Sig_x, Sig_eps, nugget) {
    .Call(`_bdrc_compute_L`, X, Sig_x, Sig_eps, nugget)
}

compute_w <- function(L, y, X, mu_x) {
    .Call(`_bdrc_compute_w`, L, y, X, mu_x)
}

compute_W <- function(L, X, Sig_x) {
    .Call(`_bdrc_compute_W`, L, X, Sig_x)
}

compute_x_u <- function(mu_x, Sig_x, n) {
    .Call(`_bdrc_compute_x_u`, mu_x, Sig_x, n)
}

compute_x <- function(x_u, W, L, sss) {
    .Call(`_bdrc_compute_x`, x_u, W, L, sss)
}

get_MCMC_summary_cpp <- function(X, h = NULL) {
    .Call(`_bdrc_get_MCMC_summary_cpp`, X, h)
}

